name: Deploy StorageApp Frontend

on: [push, workflow_dispatch]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET_NAME: paloma-frontend
      CLOUDFRONT_DISTRIBUTION_ID: E2QAJTNNC6GKXJ
      VITE_GOOGLE_CLIENT_ID: 469569207769-tg89a7isf2e6tk60nrgevqu4pevvo60o.apps.googleusercontent.com
      VITE_BACKEND_BASE_URL: https://api.palomacoding.xyz

    steps:
      - name: Clone frontend repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 sync dist/ "s3://${S3_BUCKET_NAME}/" --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
            --paths "/index.html" \
            --query 'Invalidation.Id' --output text

      - name: Deployment complete
        run: echo "Frontend Deployed Successfully..."
